# GP Setup
poetry run gp create-gp -n 'Bahrain Grand Prix' -b 'BAH' -l "Bahrain"
poetry run gp create-gp -n 'Saudi Arabian Grand Prix' -b 'SAU' -l "SaudiArabia"
poetry run gp create-gp -n 'Australian Grand Prix' -b 'AUS' -l "Australia"
poetry run gp create-gp -n 'Emilia Romagna Grand Prix' -b 'EMR' -l "Romagna"
poetry run gp create-gp -n 'Miami Grand Prix' -b 'MIA' -l "Miami"
poetry run gp create-gp -n 'Spanish Grand Prix' -b 'SPA' -l "Spain"
poetry run gp create-gp -n 'Monaco Grand Prix' -b 'MON' -l "Monaco"
poetry run gp create-gp -n 'Azerbaijan Grand Prix' -b 'AZB' -l "Azerbaijan"
poetry run gp create-gp -n 'Canadian Grand Prix' -b 'CAN' -l "Canada"
poetry run gp create-gp -n 'British Grand Prix' -b 'GBR' -l "Britian"
poetry run gp create-gp -n 'Austrian Grand Prix' -b 'AUT' -l "Austria"
poetry run gp create-gp -n 'French Grand Prix' -b 'FRA' -l "France"
poetry run gp create-gp -n 'Hungarian Grand Prix' -b 'HUN' -l "Hungary"
poetry run gp create-gp -n 'Belgian Grand Prix' -b 'BEL' -l "Belgian"
poetry run gp create-gp -n 'Italian Grand Prix' -b 'ITA' -l "Italy"
poetry run gp create-gp -n 'Singapore Grand Prix' -b 'SIG' -l "Singapore"
poetry run gp create-gp -n 'Japanese Grand Prix' -b 'JAP' -l "Japan"
poetry run gp create-gp -n 'United States Grand Prix' -b 'USA' -l "USA"
poetry run gp create-gp -n 'Mexico City Grand Prix' -b 'MEX' -l "Mexico"
poetry run gp create-gp -n 'Brazilian Grand Prix' -b 'BRA' -l "Brazil"
poetry run gp create-gp -n 'Abu Dhabi Grand Prix' -b 'ABD' -l "AbuDhabi"
poetry run gp create-gp -n 'Netherlands Grand Prix' -b 'NED' -l "Netherlands"
poetry run gp create-gp -n 'Qatar Grand Prix' -b 'QAT' -l "Qatar"
poetry run gp create-gp -n 'Las Vegas Grand Prix' -b 'LOS' -l "LasVegas"